import type { WorldDef } from './LevelTypes'
import { ROOFTOP_TEST } from '@/lib/game/maps/rooftopTest'

// Import existing solo level maps
import { MAP_2, MAP_3, MAP_4, MAP_5, MAP_6, MAP_7 } from './worldMaps'

export const WORLD_REGISTRY: WorldDef[] = [
  // ── WORLD 1: Family City ───────────────────────────────────────────────────
  {
    id:          'world1',
    name:        'Family City',
    subtitle:    'Where it all begins',
    theme:       'family_city',
    description: 'Rooftops, school hallways, playgrounds, and city lights. Learn the basics and meet the family.',
    color:       '#fbbf24',
    accentColor: '#f59e0b',
    icon:        '🏙️',
    mechanics:   ['basic', 'checkpoints', 'coins', 'traps'],
    levels: [
      {
        id: 'family-city-training-grounds', worldId: 'world1', levelNumber: 1, isBoss: false,
        title: 'Training Grounds', subtitle: 'City Rooftops at Sunset',
        difficulty: 'starter',
        description: 'Learn the basics. Jump, dodge, and make it to the finish!',
        mechanics: ['basic', 'checkpoints', 'coins'],
        musicSlot: 'familyCity',
        parTimeMs: 90000, threeStarMs: 60000,
        completionReward: { coins: 25, xp: 50, unlocks: ['bj'] },
        map: ROOFTOP_TEST,
        nextLevelId: 'family-city-chaos-factory',
      },
      {
        id: 'family-city-chaos-factory', worldId: 'world1', levelNumber: 2, isBoss: false,
        title: 'Chaos Factory', subtitle: 'Industrial Wipeout',
        difficulty: 'normal',
        description: 'Navigate the factory floor — watch for the dip!',
        mechanics: ['basic', 'checkpoints', 'coins', 'traps'],
        musicSlot: 'familyCity',
        parTimeMs: 100000, threeStarMs: 70000,
        completionReward: { coins: 35, xp: 60, unlocks: ['brae'] },
        map: MAP_2,
        nextLevelId: 'family-city-neon-skyline',
      },
      {
        id: 'family-city-neon-skyline', worldId: 'world1', levelNumber: 3, isBoss: false,
        title: 'Neon Skyline', subtitle: 'Night City Rush',
        difficulty: 'normal',
        description: 'Tight platforms above the neon city. One slip and you fall.',
        mechanics: ['basic', 'checkpoints', 'coins', 'traps'],
        musicSlot: 'familyCity',
        parTimeMs: 110000, threeStarMs: 80000,
        completionReward: { coins: 40, xp: 70, unlocks: ['xanny'] },
        map: MAP_3,
        nextLevelId: 'family-city-playroom-panic',
      },
      {
        id: 'family-city-playroom-panic', worldId: 'world1', levelNumber: 4, isBoss: false,
        title: 'Playroom Panic', subtitle: 'Toy Room Chaos',
        difficulty: 'normal',
        description: 'The playroom is alive! Giant obstacles and bouncy chaos.',
        mechanics: ['basic', 'checkpoints', 'coins', 'traps'],
        musicSlot: 'familyCity',
        parTimeMs: 115000, threeStarMs: 85000,
        completionReward: { coins: 40, xp: 75 },
        map: MAP_4,
        nextLevelId: 'family-city-family-fortress',
      },
      {
        id: 'family-city-family-fortress', worldId: 'world1', levelNumber: 5, isBoss: false,
        title: 'Family Fortress', subtitle: 'Tactical Precision',
        difficulty: 'hard',
        description: "Commander's domain. Every jump counts. No mistakes.",
        mechanics: ['basic', 'checkpoints', 'coins', 'traps', 'character_shortcuts'],
        musicSlot: 'familyCity',
        parTimeMs: 120000, threeStarMs: 90000,
        completionReward: { coins: 60, xp: 90 },
        map: MAP_5,
        nextLevelId: 'family-city-governors-domain',
      },
      {
        id: 'family-city-governors-domain', worldId: 'world1', levelNumber: 6, isBoss: true,
        title: "Governor's Domain", subtitle: 'Legacy Arena — Final Challenge',
        difficulty: 'expert',
        description: 'Only the elite finish. Tiny platforms, massive gaps. World 1 boss!',
        mechanics: ['basic', 'checkpoints', 'coins', 'traps', 'boss_chase'],
        musicSlot: 'familyCity',
        parTimeMs: 130000, threeStarMs: 100000,
        completionReward: { coins: 125, xp: 200, unlocks: ['world2', 'zaya'] },
        map: MAP_6,
        nextWorldId: 'world2',
      },
    ],
  },

  // ── WORLD 2: Chaos Labs ────────────────────────────────────────────────────
  {
    id:          'world2',
    name:        'Chaos Labs',
    subtitle:    'Experiment gone wrong',
    theme:       'chaos_labs',
    description: 'Moving conveyors, gravity pads, laser floors, and trap overload. The lab is out of control.',
    color:       '#8b5cf6',
    accentColor: '#7c3aed',
    icon:        '🧪',
    mechanics:   ['moving_platforms', 'conveyors', 'gravity_pads', 'trap_overload'],
    unlockReq:   'world1',
    levels: [
      {
        id: 'w2_l1', worldId: 'world2', levelNumber: 1, isBoss: false,
        title: 'Lab Entrance', subtitle: 'Conveyor Chaos',
        difficulty: 'normal',
        description: 'Welcome to the lab. Conveyors will push you around — learn to fight back.',
        mechanics: ['conveyors', 'coins', 'traps'],
        musicSlot: 'chaosLabs',
        parTimeMs: 100000, threeStarMs: 70000,
        completionReward: { coins: 40, xp: 70 },
        map: MAP_2, // Reuse until World 2 custom maps are designed
        comingSoon: false,
      },
      {
        id: 'w2_l2', worldId: 'world2', levelNumber: 2, isBoss: false,
        title: 'Gravity Chamber', subtitle: 'Up is Down',
        difficulty: 'hard',
        description: 'Gravity pads flip everything. Plan your jumps or fall forever.',
        mechanics: ['gravity_pads', 'coins', 'traps'],
        musicSlot: 'chaosLabs',
        parTimeMs: 110000, threeStarMs: 80000,
        completionReward: { coins: 60, xp: 90 },
        map: MAP_3,
        comingSoon: false,
      },
      {
        id: 'w2_l3', worldId: 'world2', levelNumber: 3, isBoss: false,
        title: 'Laser Grid', subtitle: 'Don\'t touch the red',
        difficulty: 'hard',
        description: 'Laser floors activate on a timer. Time your runs perfectly.',
        mechanics: ['moving_platforms', 'coins', 'traps'],
        musicSlot: 'chaosLabs',
        parTimeMs: 120000, threeStarMs: 90000,
        completionReward: { coins: 60, xp: 90 },
        map: MAP_4,
        comingSoon: true,
      },
      {
        id: 'w2_l4', worldId: 'world2', levelNumber: 4, isBoss: false,
        title: 'Trap Overload', subtitle: 'They never stop',
        difficulty: 'expert',
        description: 'Every trap active, double frequency. Pure survival.',
        mechanics: ['trap_overload', 'coins'],
        musicSlot: 'chaosLabs',
        parTimeMs: 125000, threeStarMs: 95000,
        completionReward: { coins: 90, xp: 120 },
        map: MAP_5,
        comingSoon: true,
      },
      {
        id: 'w2_l5', worldId: 'world2', levelNumber: 5, isBoss: false,
        title: 'Meltdown', subtitle: 'Lab is collapsing',
        difficulty: 'expert',
        description: 'Platforms collapse behind you. Keep moving or be left behind.',
        mechanics: ['collapsing_platforms', 'coins', 'traps'],
        musicSlot: 'chaosLabs',
        parTimeMs: 130000, threeStarMs: 100000,
        completionReward: { coins: 90, xp: 120 },
        map: MAP_6,
        comingSoon: true,
      },
      {
        id: 'w2_boss', worldId: 'world2', levelNumber: 6, isBoss: true,
        title: 'Governor AI Mech', subtitle: 'World 2 Boss',
        difficulty: 'expert',
        description: 'The Governor AI controls everything. Survive the full lab assault.',
        mechanics: ['trap_overload', 'collapsing_platforms', 'boss_chase', 'coins'],
        musicSlot: 'chaosLabs',
        parTimeMs: 140000, threeStarMs: 110000,
        completionReward: { coins: 175, xp: 250, unlocks: ['world3', 'governor'] },
        map: MAP_7,
        comingSoon: true,
      },
    ],
  },

  // ── WORLD 3: Volcano Survival ──────────────────────────────────────────────
  {
    id:          'world3',
    name:        'Volcano Survival',
    subtitle:    'Outrun the eruption',
    theme:       'volcano',
    description: 'Collapsing platforms, rising lava, falling rocks, and heat vents. Get out before it blows.',
    color:       '#ef4444',
    accentColor: '#dc2626',
    icon:        '🌋',
    mechanics:   ['collapsing_platforms', 'lava_rise', 'falling_rocks', 'heat_vents'],
    unlockReq:   'world2',
    levels: [
      {
        id: 'w3_l1', worldId: 'world3', levelNumber: 1, isBoss: false,
        title: 'Lava Fields', subtitle: 'Watch your step',
        difficulty: 'hard',
        description: 'Hot ground, narrow platforms. The lava is rising slowly.',
        mechanics: ['lava_rise', 'coins', 'traps'],
        musicSlot: 'volcano',
        parTimeMs: 110000, threeStarMs: 80000,
        completionReward: { coins: 60, xp: 90 },
        map: MAP_3,
        comingSoon: true,
      },
      {
        id: 'w3_l2', worldId: 'world3', levelNumber: 2, isBoss: false,
        title: 'Rock Rain', subtitle: 'Incoming!',
        difficulty: 'hard',
        description: 'Falling rocks crush platforms. Move fast, stay alive.',
        mechanics: ['falling_rocks', 'collapsing_platforms', 'coins'],
        musicSlot: 'volcano',
        parTimeMs: 115000, threeStarMs: 85000,
        completionReward: { coins: 60, xp: 90 },
        map: MAP_4,
        comingSoon: true,
      },
      {
        id: 'w3_l3', worldId: 'world3', levelNumber: 3, isBoss: false,
        title: 'Steam Vents', subtitle: 'Pressure is on',
        difficulty: 'expert',
        description: 'Heat vents blast you upward or sideways. Use them or lose.',
        mechanics: ['heat_vents', 'coins', 'traps'],
        musicSlot: 'volcano',
        parTimeMs: 120000, threeStarMs: 90000,
        completionReward: { coins: 90, xp: 120 },
        map: MAP_5,
        comingSoon: true,
      },
      {
        id: 'w3_l4', worldId: 'world3', levelNumber: 4, isBoss: false,
        title: 'Summit Sprint', subtitle: 'Almost there',
        difficulty: 'expert',
        description: 'The summit is near. Every platform is crumbling.',
        mechanics: ['collapsing_platforms', 'lava_rise', 'coins'],
        musicSlot: 'volcano',
        parTimeMs: 125000, threeStarMs: 95000,
        completionReward: { coins: 90, xp: 120 },
        map: MAP_6,
        comingSoon: true,
      },
      {
        id: 'w3_l5', worldId: 'world3', levelNumber: 5, isBoss: false,
        title: 'Final Ascent', subtitle: 'One last push',
        difficulty: 'chaos',
        description: 'All hazards active. Lava rising, rocks falling, vents firing. GO.',
        mechanics: ['lava_rise', 'falling_rocks', 'heat_vents', 'collapsing_platforms'],
        musicSlot: 'volcano',
        parTimeMs: 130000, threeStarMs: 100000,
        completionReward: { coins: 125, xp: 150 },
        map: MAP_7,
        comingSoon: true,
      },
      {
        id: 'w3_boss', worldId: 'world3', levelNumber: 6, isBoss: true,
        title: 'Lava Titan', subtitle: 'World 3 Boss',
        difficulty: 'chaos',
        description: 'A lava giant blocks the exit. Dodge its attacks and reach the summit.',
        mechanics: ['lava_rise', 'falling_rocks', 'boss_chase', 'coins'],
        musicSlot: 'volcano',
        parTimeMs: 140000, threeStarMs: 110000,
        completionReward: { coins: 200, xp: 300, unlocks: ['world4'] },
        map: MAP_7,
        comingSoon: true,
      },
    ],
  },

  // ── WORLD 4: Japan Neon City ───────────────────────────────────────────────
  {
    id:          'world4',
    name:        'Japan Neon City',
    subtitle:    'Precision in the neon night',
    theme:       'japan_neon',
    description: 'Rail grinds, bounce pads, teleport gates, and timed light platforms in neon Tokyo.',
    color:       '#06b6d4',
    accentColor: '#0891b2',
    icon:        '🌸',
    mechanics:   ['rail_grind', 'bounce_pads', 'teleport_gates', 'timed_platforms'],
    unlockReq:   'world3',
    levels: [
      {
        id: 'w4_l1', worldId: 'world4', levelNumber: 1, isBoss: false,
        title: 'Neon Streets', subtitle: 'Tokyo after dark',
        difficulty: 'hard',
        description: 'Bounce pads and neon platforms. Master the bounce.',
        mechanics: ['bounce_pads', 'coins', 'traps'],
        musicSlot: 'japanNeon',
        parTimeMs: 115000, threeStarMs: 85000,
        completionReward: { coins: 60, xp: 90 },
        map: MAP_3,
        comingSoon: true,
      },
      {
        id: 'w4_l2', worldId: 'world4', levelNumber: 2, isBoss: false,
        title: 'Temple Run', subtitle: 'Sacred ground',
        difficulty: 'expert',
        description: 'Ancient temple meets neon city. Teleport gates warp you forward.',
        mechanics: ['teleport_gates', 'timed_platforms', 'coins'],
        musicSlot: 'japanNeon',
        parTimeMs: 120000, threeStarMs: 90000,
        completionReward: { coins: 90, xp: 120 },
        map: MAP_4,
        comingSoon: true,
      },
      {
        id: 'w4_boss', worldId: 'world4', levelNumber: 6, isBoss: true,
        title: 'Shadow Racer', subtitle: 'World 4 Boss',
        difficulty: 'chaos',
        description: 'A shadow clone races you. Win or the city falls.',
        mechanics: ['rail_grind', 'bounce_pads', 'boss_chase'],
        musicSlot: 'japanNeon',
        parTimeMs: 140000, threeStarMs: 110000,
        completionReward: { coins: 225, xp: 350, unlocks: ['world5'] },
        map: MAP_7,
        comingSoon: true,
      },
    ],
  },

  // ── WORLD 5: Space Station X ───────────────────────────────────────────────
  {
    id:          'world5',
    name:        'Space Station X',
    subtitle:    'Zero gravity chaos',
    theme:       'space_station',
    description: 'Low gravity zones, air boost tunnels, asteroid hazards, and floating platforms.',
    color:       '#3b82f6',
    accentColor: '#2563eb',
    icon:        '🚀',
    mechanics:   ['gravity_zones', 'air_boost', 'asteroid_hazards', 'floating_platforms'],
    unlockReq:   'world4',
    levels: [
      {
        id: 'w5_l1', worldId: 'world5', levelNumber: 1, isBoss: false,
        title: 'Launch Bay', subtitle: 'First steps in space',
        difficulty: 'expert',
        description: 'Low gravity makes everything float. Adjust your jumps.',
        mechanics: ['gravity_zones', 'floating_platforms', 'coins'],
        musicSlot: 'spaceStation',
        parTimeMs: 120000, threeStarMs: 90000,
        completionReward: { coins: 90, xp: 120 },
        map: MAP_5,
        comingSoon: true,
      },
      {
        id: 'w5_boss', worldId: 'world5', levelNumber: 6, isBoss: true,
        title: 'Void Engine', subtitle: 'World 5 Boss',
        difficulty: 'chaos',
        description: 'The station core is collapsing into a void. Get out.',
        mechanics: ['gravity_zones', 'asteroid_hazards', 'boss_chase'],
        musicSlot: 'spaceStation',
        parTimeMs: 145000, threeStarMs: 115000,
        completionReward: { coins: 250, xp: 400, unlocks: ['world6'] },
        map: MAP_7,
        comingSoon: true,
      },
    ],
  },

  // ── WORLD 6: Dream Chaos ───────────────────────────────────────────────────
  {
    id:          'world6',
    name:        'Dream Chaos',
    subtitle:    'Nothing makes sense here',
    theme:       'dream_chaos',
    description: 'Fake platforms, gravity flips, time slow zones, random trap swaps, visual distortion.',
    color:       '#ec4899',
    accentColor: '#db2777',
    icon:        '🌀',
    mechanics:   ['fake_platforms', 'gravity_flip', 'time_slow', 'visual_distortion'],
    unlockReq:   'world5',
    levels: [
      {
        id: 'w6_l1', worldId: 'world6', levelNumber: 1, isBoss: false,
        title: 'Dream Entry', subtitle: 'Where am I?',
        difficulty: 'chaos',
        description: 'Some platforms vanish. Trust nothing.',
        mechanics: ['fake_platforms', 'coins', 'traps'],
        musicSlot: 'dreamChaos',
        parTimeMs: 130000, threeStarMs: 100000,
        completionReward: { coins: 125, xp: 150 },
        map: MAP_6,
        comingSoon: true,
      },
      {
        id: 'w6_boss', worldId: 'world6', levelNumber: 6, isBoss: true,
        title: 'Chaos Dimension Final', subtitle: 'World 6 Boss — The End',
        difficulty: 'chaos',
        description: 'Total chaos. Every mechanic, every trap, gravity flipping. Only legends finish.',
        mechanics: ['fake_platforms', 'gravity_flip', 'time_slow', 'boss_chase', 'trap_overload'],
        musicSlot: 'dreamChaos',
        parTimeMs: 150000, threeStarMs: 120000,
        completionReward: { coins: 500, xp: 1000 },
        map: MAP_7,
        comingSoon: true,
      },
    ],
  },
]

export const WORLDS_BY_ID = new Map(WORLD_REGISTRY.map(w => [w.id, w]))

export function getWorld(worldId: string): WorldDef | undefined {
  return WORLDS_BY_ID.get(worldId)
}

export function getLevel(worldId: string, levelId: string) {
  return getWorld(worldId)?.levels.find(l => l.id === levelId)
}

export function getAllLevels() {
  return WORLD_REGISTRY.flatMap(w => w.levels)
}
